apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: wordpress
  namespace: ${PROJECT_NS}
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None