apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
  namespace: ${PROJECT_NS}
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer